---
website_title: Julian Nadeau
website_email: julian@jnadeau.ca
website_tagline: I am a production engineer at <a href="http://shopify.com">Shopify.</a>
  I work on Developer Infrastructure.
theme: theme_1
git_user: jules2689
twitter_user: jules2689
linkedin_url: http://www.linkedin.com/pub/julian-nadeau/49/1b0/721
git_cdn_repo: jules2689/gitcdn
git_cdn_repo_url: https://jules2689.github.io/gitcdn/