development:
  adapter: postgresql
  encoding: unicode
  database: julian
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: julian_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  pool: 25
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
