interest_types:

# Videos

  - name: Youtube
    supported_schemas:
      - "http://www.youtube.com/watch?v=*"
      - "http://www.youtube.com/v/*"
    type: video
    treatment: embed
    url: "https://www.youtube.com/embed/%{id}"
    embeddable: true

  - name: Vimeo
    supported_schemas:
      - "https://vimeo.com/channels/*/*"
      - "https://vimeo.com/groups/*/videos/*"
      - "https://vimeo.com/album/*/video/*"
      - "https://vimeo.com/*"
    type: video
    url: "https://player.vimeo.com/video/%{id}?badge=0"
    embeddable: true

  - name: TED
    supported_schemas:
      - "http://www.ted.com/talks/*"
      - "http://www.ted.com/talks/lang/*/*"
      - "http://www.ted.com/index.php/talks/*"
      - "http://www.ted.com/index.php/talks/lang/*/*"
    type: video
    url: "https://embed-ssl.ted.com/talks/%{id}.html"
    embeddable: true

# Documents

  - name: Google Doc
    supported_schemas:
      - "https://docs.google.com/*"
    type: documents
    url: "https://docs.google.com/%{id}"
    embeddable: false

# Blogs and Articles

  - name: Wikipedia
    supported_schemas:
      - "http://wikipedia.com/*"
    type: article
    url: "http://wikipedia.com/%{id}"
    embeddable: false

  - name: Medium
    supported_schemas:
      - "http://medium.com/*"
    type: blog
    url: "http://medium.com/%{id}"
    embeddable: false
